name: Deploy

on: [push]

jobs:
  deploy2:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
          
      - name: Update deployment status (success)
        uses: chrnorm/deployment-action@v2
        id: deploymentTask
        with:
          task: testTask
          type: typoTask

