name: Deploy

on: [push]

jobs:
  deploy2:
    name: Deploy my app

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v1
        name: Create GitHub deployment
        id: deployment
        with:
          task: taskTest
          

